- name: Deploy Ecommerce Application
  hosts: web
  become: true
  vars_files:
    - vars/main.yml

  roles:
    - role: roles/database
      tags: db
    - role: roles/backend
      tags: backend
    - role: roles/frontend
      tags: frontend
  tasks:
    - name: Clone the app repository
      git:
        repo: 'https://github.com/your-user/ecommerce-app.git'
        dest: /home/vagrant/ecommerce-app
      tags: clone
