---
- name: Deploy Ecommerce App
  hosts: all
  become: yes

  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Run all setup blocks
      block:
        - name: Include frontend
          include_role:
            name: frontend
          tags: frontend

        - name: Include backend
          include_role:
            name: backend
          tags: backend

        - name: Include database
          include_role:
            name: database
          tags: database
