apiVersion: v1
kind: Pod
metadata:
  name: ecommerce-app
  labels:
    name: ecommerce-app
spec:
  containers:
  - name: ecommerce-app
    image: mikenyehenry/ecommerce-app:v4.0.0
   
    ports:
      - containerPort: 5000
